### ISSUE TITLE
Create install script.

### ISSUE THREAD

**Issue by foxstephen** [StephenFox1995/wttrcli#1]
Create an install script so command can be run from command line: 

e.g.
```bash
wttrcli -l Dublin -o live
```

**Comment by j-setiawan** [comment]
I can take a look at this if you'd like. Could I get more details? Did you want an installer bash script dropped in the target directory that can add something like /usr/local/bin/wttrcli that points to the jar in the target directory?

**Comment by foxstephen** [comment]
The script can be kept outside of the target directory. It can be added as a plain old install.sh to add the jar to the path, and placing the binary in /user/local/bin. So the user clones the repo, runs install.sh and can use "wttrcli" instead of "jar -jar xxx"
